site_name: Scripts Documentation
site_url: https://example.com/
nav:
  - Home: index.md
  - newproject:
    - Overview: newproject/overview.md
    - Usage: newproject/usage.md
    - Setup: newproject/setup.md
  - newproject-git: newproject-git/newproject-git.md

markdown_extensions:
  - toc:
      permalink: true
theme:
  name: material
  palette:
    # Automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    # Toggle Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.expand
