#!/bin/bash

workingDirectory="$PWD"

# What to do if url repo given
handleUrlRepo() {
    echo "Attempting to add remote GitHub repository..."


    if git remote add origin "$1"; then
        echo "Remote repsoitory successfully added."
    else 
        echo "Could not add remote repository with that URL."
        exit 2
    fi
}

# Confirm URL
confrimURL() {
    read -p "Confirm URL as \"$1\" [Y/N]: " input
    case $input in
        [yY]*)
            # Continue execution
            ;;
        *)
            echo "Remote repository for the URL was not added"
            exit 2
            ;;
    esac
}


# If no argument exists, exit
if [ "$#" -eq 0 ]
then
  echo "No arguments provided"
  exit 2
fi

while getopts "w:iu:pg" option; do
    case $option in
        w)
            workingDirectory="$workingDirectory"/"$OPTARG"
            ;;
        i) 
            # Initialize git with main branch
            cd "$workingDirectory"
            git init -b main
            ;;
        g)
            # Add a .gitignore with default files ignored
            cd "$workingDirectory"
            if [ -f "$workingDirectory/.gitignore" ]; then
                echo "Git Ignore already exists. No changes were made."
            else
                echo -e ".vscode\nbin" > .gitignore
            fi
            ;;
        u)
            # Confirm URL, add remote repository, and push
            cd "$workingDirectory"
            urlToRepo=$OPTARG
            confrimURL $urlToRepo
            handleUrlRepo $urlToRepo
            ;;
        p)
            # Stage, commit, and push everything to remote repository
            cd "$workingDirectory"
            git add .
            git commit -m "Automated commit" -m "Automated commit from newproject-git script."
            git push -u origin main
            ;;

        ?) 
            echo "Invalid option."
            exit 2
            ;;
    esac
done
